language = "C"
include_guard = "__blazesym_h_"
usize_is_size_t = true

[export]
item_types = ["globals", "enums", "structs", "unions", "typedefs", "opaque", "functions"]
exclude = ["Addr"]

[export.rename]
"Addr" = "uintptr_t"
"BlazeSymbolizer" = "blazesym"

[fn]
args = "Vertical"
rename_args = "GeckoCase"

[struct]
associated_constants_in_body = true
derive_eq = true
derive_ostream = true

[enum]
add_sentinel = false
derive_helper_methods = true
derive_ostream = true

[macro_expansion]
bitflags = true
